### ISSUE TITLE
needs refactoring

### ISSUE THREAD

**Issue by aubreywullschleger** [jojoscode/teaCozy#2]
Subtlety (for errors)! The nesting of this section is a little off. This div is empty when it should be wrapping your .teaMonthContent and .teaMonthImageContent divs instead. https://github.com/jojoscode/teaCozy/blob/master/index.html#L40-L41

**Comment by jojoscode** [comment]
I wanted the navigation to bring the viewer to the top of this section. This was my reason not to wrap the full content as it took the viewer deeper into the section instead of the top. Is there a better way to do this?
