### ISSUE TITLE
Condense slectors

### ISSUE THREAD

**Issue by aubreywullschleger** [jojoscode/teaCozy#4]
Simplify! Your styling is great as well, nice work on keeping it concise. One thing to make it even more concise would be to condense these two selectors in a single group selector, ex:
```
.teaMonthContainer, .addyContainer {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
}
```
https://github.com/jojoscode/teaCozy/blob/master/resources/css/style.css#L60-L64
https://github.com/jojoscode/teaCozy/blob/master/resources/css/style.css#L89-L93

**Comment by jojoscode** [comment]
Fixed! Thank you!
